config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pics
  root "pics#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  #acts_as_votable
  belongs_to :user
  has_attached_file :image, :styles => {:medium => "300x300"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_action :find_pic, only: [:show, :edit, :update, :destroy]

	def index
		@pics = Pic.all.order("created_at DESC")
	end

	def new
		@pic = current_user.pics.build 
	end

	def create
		@pic = current_user.pics.build (pic_params)

		if @pic.save
			redirect_to @pic, notice: "Pic posted!"
		else
			render 'new'
		end
	end

	def show
	end

	def edit

	end

	def update
		if @pic.update(pic_params)
			redirect_to @pic, notice: "Pic has been updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@pic.destroy
		redirect_to root_path
	end

	private

#	def pic_params
#		params.require(:pic).permit(:title, :description)
	#end
  	def pic_params
    	params.require(:pic).permit(:title,:description, :image)
  	end

	def find_pic
		@pic = Pic.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Instagram
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags



%body
	%nav.navbar.navbar-inverse 
		.container
			.navbar-brand= link_to "Instagram", root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-left
					%li= link_to "Post", new_pic_path
					%li= link_to "Settings", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete

			- else
				%ul.nav.navbar-nav.navbar-left
				%li= link_to "Sign Up", new_user_registration_path
				%li= link_to "Login", new_user_session_path

	.container
		-flash.each do |name, msg|
			=content_tag :div, msg, class: "alert alert-info"

		=yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true} do |f|
  - if @pic.errors.any?
    #errors
      %h2
      = pluralize(@pic.errors.count,"error")
      prevented this Pic from saving
      %ul
        - @pic.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.input :image, input_html: {class:'form-control'}
  .form-group
    = f.input :title, input_html: {class:'form-control'}
  .form-group
    = f.input :description, input_html: {class: 'form-control'}
  = f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Post
			.panel-body
				= render 'form'



app/views/pics/index.html.haml
- @pics.each do |pic|
	%h2= link_to pic.title, pic


app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Post
			.panel-body
				= render 'form'

app/views/pics/show.html.haml
%h1= @pic.title 
%p= @pic.description
%br
%p
Submitted by 
%br
= @pic.user.email
%br
= link_to "Back", root_path
= link_to 'Edit', edit_pic_path
= link_to 'Delete', pic_path, method: :delete, data: { confirm: 'Are you sure you would like to delete this post?' }
